server:
  port: 8080
spring:
  application:
    name: product-display-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 4719
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
  thymeleaf:
    prefix: classpath:/templates/
logging:
  level:
    org.flywaydb: DEBUG

fetchData:
  url: https://famme.no/products.json
